//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuctionDataModelContainer : DbContext
    {
        public AuctionDataModelContainer()
            : base("name=AuctionDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profile> ProfileSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Bid> BidSet { get; set; }
        public virtual DbSet<Rating> RatingSet { get; set; }
        public virtual DbSet<Picture> PictureSet { get; set; }
        public virtual DbSet<Features> FeaturesSet { get; set; }
    }
}
